version: "2.2.3"

volumes:
  tf_dev: {}

services:
  tf_cpu-khj:
    build:
      context: .
      dockerfile: ./dockerfiles/cpu-jupyter.Dockerfile
      
    ports:
      - "4025:4025"
    volumes:
      - tf_dev:/tf
